# Server config
server:
  port: 8001
  servlet.encoding.charset: UTF-8

# H2, JPA config
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb #jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: admin
    password: 1234
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
