# Server config
server:
  port: 8001
  servlet.encoding.charset: UTF-8

# H2, JPA config
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#      url: jdbc:h2:file:./data/test #jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
#      driverClassName: org.h2.Driver
#      username: sa
#  #    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    #    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    show-sql: true


# H2, Hikari config
#spring:
#  sql:
#    init:
#      mode: always
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    hikari:
#      # WRITE_DELAY: I/O 시간을 명확히 보여주기 위해 0초로 commit 시간을 설정
#      jdbcUrl: jdbc:h2:file:./data/test;WRITE_DELAY=0; #jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;
#      driverClassName: org.h2.Driver
#      username: sa
